name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    strategy:
      matrix:
        node_version: [12.x, 13.x, 14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}
      - name: Install dependencies
        run: npm ci
      - run: npm run format:check
      - run: npm run test -- --coverage
        env:
          CI: true
